CREATE DATABASE IF NOT EXISTS lostfound CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE lostfound;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY, nickname VARCHAR(32) NOT NULL UNIQUE, real_name VARCHAR(64) NOT NULL,
  identity_number VARCHAR(64) NOT NULL UNIQUE, identity_role ENUM('STUDENT','TEACHER','STAFF') NOT NULL,
  department VARCHAR(128) NOT NULL, grade VARCHAR(32), campus VARCHAR(128) NOT NULL,
  phone VARCHAR(32) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE,
  is_admin TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('NORMAL','FROZEN','DELETED') NOT NULL DEFAULT 'NORMAL',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_credentials (
  user_id CHAR(36) PRIMARY KEY, password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_credentials_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sessions (
  id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, expires_at TIMESTAMP NOT NULL, revoked_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS posts (
  id CHAR(36) PRIMARY KEY, owner_id CHAR(36) NOT NULL, kind ENUM('LOST_NOTICE','SEARCH_NOTICE') NOT NULL,
  title VARCHAR(80) NOT NULL, description TEXT NOT NULL, category VARCHAR(64) NOT NULL, location VARCHAR(255) NOT NULL,
  campus VARCHAR(128) NOT NULL, contact VARCHAR(255) NOT NULL, status ENUM('ACTIVE','RESOLVED','CLOSED') NOT NULL DEFAULT 'ACTIVE',
  resolved_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_posts_owner FOREIGN KEY (owner_id) REFERENCES users(id), INDEX ix_posts_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS post_images (
  id CHAR(36) PRIMARY KEY, owner_id CHAR(36) NOT NULL, object_key VARCHAR(512) NOT NULL UNIQUE, public_url VARCHAR(1024) NOT NULL,
  content_type VARCHAR(64) NOT NULL, size_bytes BIGINT NOT NULL, status ENUM('TEMPORARY','ATTACHED') NOT NULL DEFAULT 'TEMPORARY',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_images_owner FOREIGN KEY (owner_id) REFERENCES users(id), INDEX ix_images_owner_status (owner_id, status)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS post_image_links (
  post_id CHAR(36) NOT NULL, image_id CHAR(36) NOT NULL UNIQUE, position INT NOT NULL,
  PRIMARY KEY (post_id, image_id), CONSTRAINT fk_link_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_link_image FOREIGN KEY (image_id) REFERENCES post_images(id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS claims (
  id CHAR(36) PRIMARY KEY, post_id CHAR(36) NOT NULL, applicant_id CHAR(36) NOT NULL, answer VARCHAR(500) NOT NULL,
  status ENUM('PENDING','COMPLETED') NOT NULL DEFAULT 'PENDING', completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_claim_post FOREIGN KEY (post_id) REFERENCES posts(id), CONSTRAINT fk_claim_applicant FOREIGN KEY (applicant_id) REFERENCES users(id),
  INDEX ix_claims_post_status (post_id, status)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS clues (
  id CHAR(36) PRIMARY KEY, post_id CHAR(36) NOT NULL, author_id CHAR(36) NOT NULL, content VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_clue_post FOREIGN KEY (post_id) REFERENCES posts(id), CONSTRAINT fk_clue_author FOREIGN KEY (author_id) REFERENCES users(id),
  INDEX ix_clues_post_created (post_id, created_at)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS post_comments (
  id CHAR(36) PRIMARY KEY, post_id CHAR(36) NOT NULL, user_id CHAR(36) NOT NULL,
  content VARCHAR(200) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_comments_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_post_comments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX ix_post_comments_post_created (post_id, created_at), INDEX ix_post_comments_user_created (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_reads (
  user_id CHAR(36) NOT NULL, notification_id VARCHAR(160) NOT NULL,
  read_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, notification_id),
  CONSTRAINT fk_notification_reads_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX ix_notification_reads_user_read (user_id, read_at)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
